Repository gnudatalanguage/gdl, pull requests merged in 2018-04, with the labels that each got.

#37 Thomas patches
  src/basic_fun.cpp
  src/basic_fun_cl.cpp
  src/file.cpp
  src/file.hpp
  src/initsysvar.cpp
  src/libinit.cpp
Labels: windows

#158 Temporarily disable test_bytscl.pro and test_modulo.pro ??? (as of now the master branch CI fails!)
  .travis.yml
Labels: kludge, priority!

#168 removin bogus (typo) condition from travis file
  .travis.yml
Labels: cleanup

#25 redirecting users to github for issue tracking
  README
  src/gdl.cpp
  src/nullgdl.cpp
  src/pro/utilities/idlneturl__define.pro
  src/pro/utilities/idlsysmonitorinfo__define.pro
  src/typedefs.hpp
Labels: docs

#166 Correct some clang warnings
  src/basegdl.hpp
  src/basic_fun.cpp
  src/basic_pro_jmg.cpp
  src/convert2.cpp
  src/datatypes_minmax.cpp
  src/gdlwidget.cpp
  src/graphicsdevice.hpp
  src/gsl_fun.cpp
  src/gzstream.hpp
  src/hdf5_fun.cpp
  src/hdf_fun.cpp
  src/hdf_pro.cpp
  src/ifmt.cpp
  src/list.cpp
  src/magick_cl.cpp
  src/matrix_invert.cpp
  src/minmax_include.cpp
  src/ncdf_var_cl.cpp
  src/plotting_convert_coord.cpp
  src/plotting_plot.cpp
  src/saverestore.cpp
  src/triangulation.cpp
  src/widget.cpp
Labels: cleanup

#182 removing rk4 code that was commented out long time ago
  src/libinit_jmg.cpp
  src/math_fun_jmg.cpp
Labels: cleanup

#190 Pm bug
  src/print.cpp
Labels: todo-test
