Repository gnudatalanguage/gdl, pull requests merged in 2018-06, with the labels that each got.

#274 Use size_t for string positions
  src/dinterpreter.cpp
  src/gdlc.g
Labels: todo-generated-files

#322 OpenMP option in CMake
  .travis.yml
  CMakeLists.txt
  appveyor.yml
Labels: todo-fix

#328 Patch help, includefirst.hpp for WIN32
  src/gdlhelp.cpp
  src/includefirst.hpp
Labels: todo-test
